PRODUCT_BRAND_NAME="Apla"
DB_HOST="apla-db"
DB_NAME_PREFIX="apla"
DB_USER="postgres"
DB_PASSWORD="apla"
CENT_URL="http://apla-cf:8000"
BLEX_REPO_URL="https://github.com/AplaProject/blockexplorer"
BLEX_BRANCH="v0.3.3"
