PRODUCT_BRAND_NAME="Apla"
DB_HOST="apla-db"
DB_NAME_PREFIX="apla"
DB_USER="postgres"
DB_PASSWORD="apla"
CENT_URL="http://apla-cf:8000"

BLEX_REPO_URL="https://github.com/AplaProject/blockexplorer"
BLEX_BRANCH="v0.3.3"
BLEX_DB_NAME_PREFIX="apla_blex_"
BLEX_DB_HOST="apla-db"
BLEX_DB_PORT="$DB_PORT"
BLEX_DB_USER="postgres"
BLEX_DB_PASSWORD="apla"
BLEX_REDIS_URL="redis://apla-rq:6379/0"
BE_API_URL_PREFIX="http://apla-bf"
